name: "Install dependencies"
description: "Prepare repository and all dependencies"

inputs:
  node-version:
    description: "Node.js version to use"
    default: "24"
  install-playwright:
    description: "Install Playwright browsers"
    default: true
    required: false
    type: boolean

runs:
  using: "composite"
  steps:
    - name: Setup nodejs
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: "npm"

    - name: Install dependencies
      run: npm ci --ignore-scripts --audit=false
      shell: bash

