version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore"
      include: "scope"
    ignore:
      - dependency-name: "lightweight-charts"
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@rslib/core"
        update-types: ["version-update:semver-minor"]
    groups:
      react-packages:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
    labels:
      - "dependencies"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
