name: "Release"
description: "Release a new version of the library"

inputs:
  tag:
    description: "Tag to release"
    required: true

runs:
  using: "composite"
  steps:
    - name: Check that was not published on npm
      working-directory: lib
      run: | # zizmor: ignore[template-injection] release tags come from trusted workflow dispatch context
        VERSION=$(echo "${{ inputs.tag }}" | sed 's/^v//')
        PACKAGE_NAME=$(jq -r .name package.json)
        if ! npm view "$PACKAGE_NAME@$VERSION" > /dev/null 2>&1; then
          echo "✅ Version $VERSION is not published on npm."
        else
          echo "❌ ERROR: Version $VERSION already exists on npm! Please use a different version."
          exit 1
        fi
      shell: bash

    - name: Check npm publishing (dry run)
      working-directory: lib
      run: npm publish --dry-run
      shell: bash

    - name: Check JSR publishing (dry run)
      working-directory: lib
      run: npx jsr publish --dry-run
      shell: bash

    - name: Create a new release
      uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v3.0.0
      with:
        tag_name: ${{ inputs.tag }}
        name: ${{ inputs.tag }}
        make_latest: true
        generate_release_notes: true

    - name: Publish package on npm
      working-directory: lib
      run: npm publish
      shell: bash

    - name: Publish package on jsr
      working-directory: lib
      run: npx jsr publish
      shell: bash
