name: "Check dry publishing"
description: "Checks npm and JSR dry publishing for the library package"

inputs:
  package-directory:
    description: "Directory of the package to check"
    required: false
    default: "lib"

runs:
  using: "composite"
  steps:
    - name: Check npm publishing (dry run)
      working-directory: ${{ inputs.package-directory }}
      run: npm publish --dry-run
      shell: bash

    - name: Check JSR publishing (dry run)
      working-directory: ${{ inputs.package-directory }}
      run: npx jsr publish --dry-run
      shell: bash
