name: "Deploy examples"
description: "Deploy the examples to GitHub Pages"

inputs:
  keep-files:
    description: "Keep existing files in the gh-pages branch"
    required: false
    default: "false"
  branch:
    description: "Branch to deploy to"
    required: false
    default: "gh-pages"
  token:
    description: "GitHub token"
    required: true

runs:
  using: "composite"
  steps:
    - name: Deploy
      uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4.1.0
      with:
        github_token: ${{ inputs.token }}
        publish_dir: examples/dist
        publish_branch: ${{ inputs.branch }}
        allow_empty_commit: true
        enable_jekyll: false
        keep_files: ${{ inputs['keep-files'] }}
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
