name: "Lint"
description: "Lints the code in the repo"

inputs:
  check-commits:
    description: "Check if the commits follow the conventional commits specification"
    required: false
    default: "false"
  commit_base_sha:
    description: "Base commit SHA to exclude when linting PR commits"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Lint
      run: npm run lint
      shell: bash

    - name: Format
      run: npm run format
      shell: bash

    - name: Check for unused files, dependencies, and exports
      run: npm run knip
      shell: bash

    - name: Lint commits
      if: ${{ inputs.check-commits == 'true' }}
      env:
        COMMITLINT_FROM_REF: ${{ inputs.commit_base_sha }}
      run: |
        git config --global --add safe.directory "$(pwd)"
        npm run lint:commits
      shell: bash

    - name: Check markdown links
      run: npm run check:md-links
      shell: bash

    - name: Validate JSON and YAML files
      uses: GrantBirki/json-yaml-validate@9bbaa8474e3af4e91f25eda8ac194fdc30564d96 # v4.0.0

    - name: Lint shell scripts with ShellCheck
      uses: ludeeus/action-shellcheck@00cae500b08a931fb5698e11e79bfbd38e612a38 # v2.0.0
      with:
        scandir: "."
        ignore_paths: "node_modules dist coverage .pnpm-store"
        severity: error
