name: Check Versions in Sync

# This workflow ensures that the versions in package.json, jsr.json, and version.ts are in sync.

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  check-versions-in-sync:
    name: Check Versions in Sync
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: ".nvmrc"

      - name: Check versions in sync
        uses: ./.github/actions/check-versions-in-sync
        with:
          PACKAGE_JSON: lib/package.json
          JSR_JSON: lib/jsr.json
          VERSION_FILE: lib/src/version.ts
