name: Release
description: Builds and runs tests for the code in the repo

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

build:
  name: Build
  runs-on: ubuntu-latest

  steps:
    - name: Clone repository
      uses: actions/checkout@v4

    - name: Install dependencies
      uses: ./.github/actions/install-dependencies

    - name: Build
      run: npm run build
