name: Release
# Create a tag with a valid SemVer version number
# and then run this workflow to release a new version of the library
# and deploy the examples to GitHub Pages

on:
  workflow_dispatch:
    inputs:
      deploy-examples:
        description: "Deploy the examples to GitHub Pages"
        required: false
        default: true
        type: boolean

concurrency:
  group: ${{ github.workflow }}-${{ github.run_id }}
  cancel-in-progress: true

jobs:
  check-semver-tag:
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.check-semver-tag.outputs.tag_name }}
    steps:
      - name: Check semver tag
        id: check-semver-tag
        run: |
          TAG_NAME=${GITHUB_REF##*/}
          echo "Checking if the tag $TAG_NAME is a valid SemVer tag..."

          if [[ ! "$TAG_NAME" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Error: Tag $TAG_NAME is not a valid SemVer tag"
            exit 1
          fi

          echo "The tag $TAG_NAME is a valid SemVer tag."

          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
        shell: bash

  release:
    needs: check-semver-tag
    name: Release
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ukorvl/custom-github-actions-playwright:latest
      options: --user pwuser
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Check Changelog
        uses: ukorvl/custom-github-actions/check-version-changelog@v1
        with:
          PACKAGE_JSON: "lib/package.json"
          CHANGELOG_FILE: "lib/CHANGELOG.md"

      - name: Check versions in sync
        uses: ./.github/actions/check-versions-in-sync
        with:
          PACKAGE_JSON: lib/package.json
          JSR_JSON: lib/jsr.json
          VERSION_FILE: lib/src/version.ts

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
        with:
          setup-node: false # don't need to setup node, it's already in the container

      - name: Lint
        uses: ./.github/actions/lint
        with:
          check-commits: false

      - name: Build
        uses: ./.github/actions/build

      - name: Run all tests
        run: |
          export CI=true
          export DISABLE_EXTERNAL_LINK_TEST=false
          npm run test:all
        shell: bash

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: examples/tests/e2e/output/playwright-report
          if-no-files-found: "warn"
          retention-days: 30

      - name: Create a new release
        uses: ./.github/actions/create-release
        with:
          tag: ${{ needs.check-semver-tag.outputs.tag_name }}
          npm-token: ${{ secrets.NPM_AUTH_TOKEN }}

  deploy:
    name: Deploy examples
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: release
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
        with:
          setup-node: true

      - name: Build
        uses: ./.github/actions/build
        with:
          base-path: /lightweight-charts-react-components
          deploy: true

      - name: Deploy
        uses: ./.github/actions/deploy-examples
        with:
          keep-files: true
          branch: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}
